#logging:
#  config: classpath:logback-${spring.profiles.active}.xml

spring:
  datasource: 
    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false  main:    allow-bean-definition-overriding: true  messages:    basename: validation
    encoding: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false  profiles:    include:    - oauth  session:    store-type: jdbc  h2:    console:      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0

---
spring:
  profiles: production
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 1234